# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

baseURL: ""

title: "Quire Docs"
languageCode: "en-us"
theme: "default"
publishDir: site

footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
# googleAnalytics: "UA-8087223-38"
pygmentsUseClasses: true # must be set to style code samples

pluralizeListTitles: true
disableKinds:
  - "home"
  - "section"
  - "taxonomy"
  - "taxonomyTerm"

markup:
  goldmark:
    renderer:
      unsafe: true # allows HTML tags within Markdown file

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  licenseIcons: true
  pageLabelDivider: ". "
  citationPageLocationDivider: ", "
  contributorByline: name-title # name | name-title | false
  displayBiblioShort: true
  imageDir: "img"
  tocType: full
  menuType: full
  prevPageButtonText: "Back"
  nextPageButtonText: "Next"
  entryPageSideBySideLayout: false
  entryPageObjectLinkText: "View in Collection"
  figureLabelLocation: below # below | on-top
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  citationPopupStyle: text # text | icon
  GoogleAnalytics4: GTM-NRDC63K
  #
  # These are custom attributes for this project:
  menuView: fixed # fixed | hidden (default)
  menuSide: right # left | right (default)
  navView: main-pages # none | tagline | main-pages | next-prev (default)
  navType: short # short | full (default)
  footerButtons: false
  repository: https://github.com/thegetty/quire-docs/
  defaultBranch: main
